### ISSUE TITLE
Enhancement/Fix : make it Opt-In

### ISSUE THREAD

**Issue by KurtB03** [devlooped/SponsorLink#52] opened 2023-08-16 12:18 UTC
The recent discussion went a little off the rails. And because i see parts of both arguments I was wondering what stands in the way of the obvious solution : Opt-In.

Silently checking personal data is a NO GO, just ask for it. 

It should be a reasonable default assumption that the user isn't a sponsor, and treat them as such. Sponsors interested in the linked benefits, can authenticate themselves.

**Comment by kzu** [comment] 2023-08-17 18:43
Mostly a duplicate of https://github.com/devlooped/SponsorLink/issues/31, I think.

If you have no sponsorlink file, you're assumed not to be a sponsor. If you install the GH CLI extension and run the `gh sponsors link` command, you will need two things:

1. Install the [GH App](https://github.com/apps/sponsorlink) (to your GH account, not download anything) that asks for explicit email sharing permission (as it does today)
2. The tool will *also* remind you about this but explain how it will be made secure by using k-anonimity for the (improved) hashes too.

**Closed by kzu** 2023-08-17 18:43 UTC
Labels: bug
